### ISSUE TITLE
Make website responsive on mobile and desktop... or not cutoff/broken 

### ISSUE THREAD

**Issue by charliecf** [charliecf/angelcalc#21]
![2017-04-17-110939_2532x1213_scrot](https://cloud.githubusercontent.com/assets/6413808/25093119/c28d53e2-235e-11e7-9b96-9dabbd827e5f.png)
![screenshot_20170417-111128](https://cloud.githubusercontent.com/assets/6413808/25093143/d82c7ab6-235e-11e7-8d9a-ef5a55db16c8.png)

**Comment by yitongzhang** [comment]
Darn it. Can't believe i missed this.
