### ISSUE TITLE
Number formatting needs work

### ISSUE THREAD

**Issue by yitongzhang** [charliecf/angelcalc#7]
Need to implement:
- comma zero separators 
- max 1 decimal
- dollar sign / units in general?
- number incrementor: do we want it? if we do, it should increment by more than 1 at a time lol

**Comment by charliecf** [comment]
for percentage i think more than 1 decimal? or actually nvm, on the backend we can optimize for more, but it doesn't really matter as long as shares # is correct

**Comment by charliecf** [comment]
@yitongzhang for post-option pool % I think we put it as % rather than <1

**Comment by charliecf** [comment]
Changed decimal input into number as a %
whatever the input value is... putting it through `divide by 100`
