### ISSUE TITLE
site not responsive at all

### ISSUE THREAD

**Issue by yitongzhang** [charliecf/angelcalc#8]
make it so!

**Comment by charliecf** [comment]
![2017-03-18-205027_2560x1440_scrot](https://cloud.githubusercontent.com/assets/6413808/24077207/a08dd766-0c1c-11e7-98e7-4f64d6feb000.png)

I thought pre/post valuation was missing, turns out... it's off the page LOL.

I think this ties into issue #7

**Comment by charliecf** [comment]
![2017-03-18-205742_2560x1440_scrot](https://cloud.githubusercontent.com/assets/6413808/24077247/a267ee2c-0c1d-11e7-8bcd-682629f50355.png)

Not quite responsive I see...

**Comment by yitongzhang** [comment]
lulz. this lack of responsiveness is SAD! Gonna fix.

**Comment by yitongzhang** [comment]
Made a first pass at responsive. :) Not perfect, but doesn't break horribly for now
