### ISSUE TITLE
Can't add the same note twice

### ISSUE THREAD

**Issue by yitongzhang** [charliecf/angelcalc#9]

**Comment by charliecf** [comment]
I think this is because you're creating an `ID` for each note's div. ID's can't be duplicated... perhaps you should use class for the styling there

**Currently:**
`<article id="YC Standard Note">`

**Comment by yitongzhang** [comment]
Is it not better to create a unique ID every time? Won't you want to reference each instance of the same type of note separately? I propose:

<article id="YCStandardNote1">
<article id="YCStandardNote2">
